### ISSUE TITLE
Data set problem

### ISSUE THREAD

**Issue by yyqxnice** [iffiX/PGPPortfolio-pytorch#3]
Hello, the data set I downloaded is always 162M, can you share the complete data set when you ran the code before to me, thank you.

**Comment by iffiX** [comment]
@yyqxnice Here is the link: https://drive.google.com/file/d/1ITKBNLyTWhtQDg8Lv3hQzM31NdWSL5kG/view?usp=sharing

_Originally posted by @iffiX in https://github.com/iffiX/PGPortfolio-pytorch/issues/2#issuecomment-886774591_
