### ISSUE TITLE
GPUs in parallel

### ISSUE THREAD

**Issue by yyqxnice** [iffiX/PGPPortfolio-pytorch#5]
Thank you for your answer to my question, it is very useful after I read it. My main problem now is cuda out of memory. I tried to modify the device to cpu on the command line but an error was reported, so I want to use two GPUs in parallel to solve this problem. Which part of the code needs to be modified for this operation?

**Comment by iffiX** [comment]
Sorry, but we don't provide that type of support. If you really need to do that, the problem should be easy to solve by splitting that 2760 size sample into multiple parts and then evaluate metrics on each part, there is no need to use multiple GPUs. Also, the program should be safe to run on a 4GB GPU as we have tested.

And as a recommendation, for any problem related to using the default functionality of the code, it is always a good practice to include **details of your execution process and error** when you post an issue, to any repository shared on Github. For example, what is your command? The console output & python stack trace? when you say:


> I tried to modify the device to cpu on the command line but an error was reported.

That would be very helpful for contributing to the code and helping others with the same problem.
