### ISSUE TITLE
About the config file

### ISSUE THREAD

**Issue by yyqxnice** [iffiX/PGPPortfolio-pytorch#6]
Thank you for your previous answers to my question, it was very helpful to me. I have a test/config file and a config file, but I found two problems when I ran it. 
(1) I tried to split the 2760 size sample by modifying the start_date and end_date of the two config files according to your previous answer. My config file start_date is 2017/3/27, end_date is 2017/4/27, but I The start_date set for the test/config file is 2014/11/01 and the end_date is 2016/10/28, but once main.py is run, the start and end time of the test/config file will become the same as the config file. 
(2) If I change the time of the config file to start_date is 2015/05/01 and end_date is 2016/05/01, an error message will be reported (the length of selected coins 7 is not equal to expected 11). 
So, I am very curious, how should I split the 2760 samples?

**Comment by iffiX** [comment]
(1) Hi, by "splitting" I did not mean splitting by config file, that won't work. In case you really need this solution, below modification will work:
In `nnagent/tradertrainer.py`
```
    def training_step_end(self, training_output):
        # Manually test after each training step.
        # Note: _test_set_X, _test_set_y, etc. are registered buffers.
        fast_train = self._train_config["fast_train"]

        self._net.eval()

        batch_size = self._test_set_X.shape[0]
        new_w_list = []
        for start in range(0, batch_size, 100):
            end = min(start + 100, batch_size)
            new_w = self._net(self._test_set_X[start:end], self._test_set_last_w[start:end])
            new_w_list.append(new_w)
        new_w = t.cat(new_w_list, dim=0)
```

However, this is not recommended, as I mentioned before, most consumer-grade GPUs after 2016 like GTX1060 will have sufficient memory for training directly, unless you have modified the network part config file. Again, please provide **full configuration file, execution command, platform & hardware information, console output**, etc for me to help you, your explanation:

>  I tried to split the 2760 size sample by modifying the start_date and end_date of the two config files according to your previous answer. My config file start_date is 2017/3/27, end_date is 2017/4/27, but I The start_date set for the test/config file is 2014/11/01 and the end_date is 2016/10/28, but once main.py is run, the start and end time of the test/config file will become the same as the config file.

Is not precise and does not show what is actually run by you, and I can only guess what's happening under the hood, a good issue is [like this one](https://github.com/pytorch/pytorch/issues/62878#issue-962428554), please be sure to include enough information.

(2) "the length of selected coins 7 is not equal to expected 11" is happening because you have modified the number of coins used in portfolio selection, which is controlled by:
```
"input":{
    ...
    "coin_number":11,   // you probably modified this to 7
}
```
And the framework does not allow portfolio reselection after you have downloaded information from Poloniex. You need to restart from the beginning and remove cached files before using a new configuration.

**Comment by yyqxnice** [comment]
> （1）嗨，通过"拆分"我并不意味着通过配置文件分裂，这不会工作。如果您真的需要此解决方案，请在下面修改将工作：
> `nnagent/tradertrainer.py`
> 
> ```
>     def training_step_end(self, training_output):
>         # Manually test after each training step.
>         # Note: _test_set_X, _test_set_y, etc. are registered buffers.
>         fast_train = self._train_config["fast_train"]
> 
>         self._net.eval()
> 
>         batch_size = self._test_set_X.shape[0]
>         new_w_list = []
>         for start in range(0, batch_size, 100):
>             end = min(start + 100, batch_size)
>             new_w = self._net(self._test_set_X[start:end], self._test_set_last_w[start:end])
>             new_w_list.append(new_w)
>         new_w = t.cat(new_w_list, dim=0)
> ```
> 
> 但是，正如我之前提到的，2016 年之后，大多数消费者级 GPU（如 GTX1060）将有足够的内存直接用于培训，除非您修改了网络部分配置文件。再次，请提供**完整的配置文件，执行命令，平台和硬件信息，控制台输出**等，我来帮助你，你的解释：
> 
> > 我试图通过修改两个配置文件的start_date和end_date来分割 2760 大小的样本，根据您之前的答案。我的配置文件start_date是 2017/3/27， end_date是 2017/4/27， 但我 测试/配置文件设置的start_date设置为 2014/11/01，end_date是 2016/10/28， 但一旦运行 main.py，测试/配置文件的开始和结束时间将变得与配置文件相同。
> 
> 是不精确的，不显示什么实际上是由你运行，我只能猜测在引擎盖下发生了什么，一个很好的问题是这样的，请[务](https://github.com/pytorch/pytorch/issues/62878#issue-962428554)必包括足够的信息。
> 
> （2） "选定硬币 7 的长度不等于预期的 11" 正在发生， 因为您修改了投资组合选择中使用的硬币数量， 由以下控制：
> 
> ```
> "input":{
>     ...
>     "coin_number":11,   // you probably modified this to 7
> }
> ```
> 
> 在您从 Poloniex 下载信息后，该框架不允许进行投资组合重新选。在使用新配置之前，您需要从头重新启动并删除缓存文件。



> (1) Hi, by "splitting" I did not mean splitting by config file, that won't work. In case you really need this solution, below modification will work:
> In `nnagent/tradertrainer.py`
> 
> ```
>     def training_step_end(self, training_output):
>         # Manually test after each training step.
>         # Note: _test_set_X, _test_set_y, etc. are registered buffers.
>         fast_train = self._train_config["fast_train"]
> 
>         self._net.eval()
> 
>         batch_size = self._test_set_X.shape[0]
>         new_w_list = []
>         for start in range(0, batch_size, 100):
>             end = min(start + 100, batch_size)
>             new_w = self._net(self._test_set_X[start:end], self._test_set_last_w[start:end])
>             new_w_list.append(new_w)
>         new_w = t.cat(new_w_list, dim=0)
> ```
> 
> However, this is not recommended, as I mentioned before, most consumer-grade GPUs after 2016 like GTX1060 will have sufficient memory for training directly, unless you have modified the network part config file. Again, please provide **full configuration file, execution command, platform & hardware information, console output**, etc for me to help you, your explanation:
> 
> > I tried to split the 2760 size sample by modifying the start_date and end_date of the two config files according to your previous answer. My config file start_date is 2017/3/27, end_date is 2017/4/27, but I The start_date set for the test/config file is 2014/11/01 and the end_date is 2016/10/28, but once main.py is run, the start and end time of the test/config file will become the same as the config file.
> 
> Is not precise and does not show what is actually run by you, and I can only guess what's happening under the hood, a good issue is [like this one](https://github.com/pytorch/pytorch/issues/62878#issue-962428554), please be sure to include enough information.
> 
> (2) "the length of selected coins 7 is not equal to expected 11" is happening because you have modified the number of coins used in portfolio selection, which is controlled by:
> 
> ```
> "input":{
>     ...
>     "coin_number":11,   // you probably modified this to 7
> }
> ```
> 
> And the framework does not allow portfolio reselection after you have downloaded information from Poloniex. You need to restart from the beginning and remove cached files before using a new configuration.

Hello, when I just wanted to answer your question, I found that the issue was closed.I am using a linux system, cuda version: 10.2, GTX1080. I tried to run this program on a 3090 server, but 3090 supports cuda11.0 at least, so it can’t run. This is my test/config.This config is in the created test folder.
![test](https://user-images.githubusercontent.com/87406827/128587745-4ef7ef8e-b537-400c-ab68-027bc450e075.png)


I use the same command line and another config file as you put out on github.This config file is side by side with the main file.Run (python main.py --mode train --working_dir test --device=0 --offline) this command line can be trained normally, when I further change the start and end time of the config you gave on github to 2017/ 3/27 and 2017/4/27.
Thank you very much for your answers to my previous questions.This has benefited me a lot.I have problems afterwards and hope to communicate with you more.

**Comment by iffiX** [comment]
Hi, your config file can't be theoretically run since the "feature_number" of the input region is 3 while the "filter_number" of your first convolution layer is 1. If this is corrected then the config file will run correctly. For both date ranges, the first one from 2014/03/27 to 2017/04/27 and the second one from 2017/ 3/27 to 2017/4/27, works fine on my side, also I have tested using your updated requirements.txt. Sorry, but I really can't reproduce your issue.
